@ECHO OFF
SETLOCAL
SET PATH=C:\PROGRA~1\Mono-1.0.5\bin;%PATH%
SET MONO_PATH=C:\PROGRA~1\Mono-1.0.5\lib
SET MONO_CFG_DIR=C:\PROGRA~1\Mono-1.0.5\etc
SET MONO_EXTERNAL_ENCODINGS=ISO8859_1
"C:\PROGRA~1\Mono-1.0.5\lib\mono.exe" MediaNET.exe %*
ENDLOCAL
